import { ModelObserver } from "../../libs/model.js";
const observer=ModelObserver(),W=1240,H=760,PAGE=50;
const ROMAN={1:"I",2:"II",3:"III",4:"IV",5:"V",6:"VI",7:"VII",8:"VIII",9:"IX",10:"X",11:"XI"};
const ICON_ROOT="icons/";
const NATION_ASSETS={china:"china.png",czech:"czech.png",france:"france.png",germany:"germany.png",italy:"italy.png",japan:"japan.png",poland:"poland.png",sweden:"sweden.png",uk:"uk.png",usa:"usa.png",ussr:"ussr.png"};
const TYPES={"lighttank":["ЛТ","lightTank"],"mediumtank":["СТ","mediumTank"],"heavytank":["ТТ","heavyTank"],"at-spg":["ПТ-САУ","AT-SPG"],"spg":["САУ","SPG"]};
const M={1:"img://gui/maps/icons/achievement/48x48/markOfMastery1.png",2:"img://gui/maps/icons/achievement/48x48/markOfMastery2.png",3:"img://gui/maps/icons/achievement/48x48/markOfMastery3.png",4:"img://gui/maps/icons/achievement/48x48/markOfMastery4.png"};
let data={rows:[],total:0},lastPayload=null,lastW=0,lastH=0,state={levels:new Set(),nations:new Set(),types:new Set(),owned:false,search:"",page:1,sort:"mastery",desc:true,scrollTop:0};
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}
function num(v){let n=Number(v)||0;return n>0?Math.round(n).toLocaleString("en-US"):"—";}
function nameOf(r){let v=String(r&&r.vehicleName!=null?r.vehicleName:(r&&r.name!=null?r.name:"" )).trim();return v||(r&&r.id?"#"+r.id:"—");}
function img(src,cls){return '<img class="'+cls+'" src="'+src+'" onerror="this.style.display=\'none\'">';}
function mastery(n,cls){return M[Number(n)]?img(M[Number(n)],cls):'<span class="mastery-none">—</span>';}
function nation(n){n=String(n||"").toLowerCase();let asset=NATION_ASSETS[n];return '<span class="native-nation">'+(asset?img(ICON_ROOT+asset,'native-nation-img'):'')+'</span>';}
function typeIcon(t,label){let x=TYPES[String(t||"").toLowerCase()]||["—",""];return '<span class="native-type">'+(x[1]?img(ICON_ROOT+x[1]+'.png','native-type-img'):'')+(label?'<span class="native-type-label">'+esc(x[0])+'</span>':'')+'</span>';}
function resize(w,h){w=Math.max(W,Math.round(Number(w)||W));h=Math.max(H,Math.round(Number(h)||H));if(w===lastW&&h===lastH)return;lastW=w;lastH=h;try{if(viewEnv.freezeTextureBeforeResize)viewEnv.freezeTextureBeforeResize();}catch(e){}try{if(viewEnv.resizeViewPx)viewEnv.resizeViewPx(w,h);else if(viewEnv.resizeViewRem)viewEnv.resizeViewRem(w,h);}catch(e){}}
function closeStats(){try{let m=observer.model;if(m&&m.onClose)m.onClose({});}catch(e){}}
function reset(){state.scrollTop=0;let r=document.querySelector('.rows');if(r)r.scrollTop=0;}
function root(){let r=document.getElementById('stats-root');if(r)return r;r=document.createElement('div');r.id='stats-root';r.innerHTML='<div class="shell"><div class="topbar"><div><div class="title">Статистика майстерності</div><div class="subtitle">Танки та пороги досвіду</div></div><div class="spacer"></div><input class="search" placeholder="Пошук танка…"><button class="close"><i></i></button></div><div class="list-screen"><div class="filters"><div class="filter-row filter-primary"><span class="label">Рівень</span><div class="chips level-chips"></div><span class="type-label">Тип</span><div class="chips type-chips"></div><button class="chip owned-toggle" title="Тільки техніка в гаражі"><span class="garage-filter-glyph"><i></i></span></button></div><div class="filter-row nations"><span class="label">Нація</span><div class="chips nation-chips"></div></div></div><div class="content"><div class="head"><span>#</span><span data-sort="name">Танк</span><span data-sort="level">Рів.</span><span data-sort="type">Тип</span><span data-sort="mastery">Клас</span><span data-sort="thirdClass">'+mastery(1,'header-mastery-icon')+'</span><span data-sort="secondClass">'+mastery(2,'header-mastery-icon')+'</span><span data-sort="firstClass">'+mastery(3,'header-mastery-icon')+'</span><span data-sort="aceTanker">'+mastery(4,'header-mastery-icon')+'</span></div><div class="rows"></div><div class="footer"><span class="count"></span><span class="detail-hint">50 танків на сторінці</span><div class="pager"></div></div></div></div></div>';document.body.appendChild(r);r.querySelector('.close').onclick=closeStats;r.querySelector('.search').oninput=e=>{state.search=String(e.target.value||'').toLowerCase();state.page=1;reset();renderRows(true);};r.querySelector('.owned-toggle').onclick=e=>{state.owned=!state.owned;e.currentTarget.classList.toggle('on',state.owned);state.page=1;reset();renderRows(true);};Array.from(r.querySelectorAll('.head [data-sort]')).forEach(x=>x.onclick=function(){let k=this.getAttribute('data-sort');if(state.sort===k)state.desc=!state.desc;else{state.sort=k;state.desc=k!=="name";}state.page=1;reset();renderRows(true);});let rows=r.querySelector('.rows');rows.onscroll=function(){state.scrollTop=this.scrollTop||0;};rows.addEventListener('wheel',function(e){let d=typeof e.deltaY==='number'?e.deltaY:-(e.wheelDelta||0);if(!d)return;e.preventDefault();e.stopPropagation();this.scrollTop=Math.max(0,this.scrollTop+(d>0?-81:81));state.scrollTop=this.scrollTop||0;});return r;}
function unique(a){return a.filter((v,i)=>a.indexOf(v)===i);}
function chips(sel,vals,set,fn,cls){let w=root().querySelector(sel);w.innerHTML='';vals.forEach(v=>{let b=document.createElement('button');b.className='chip '+cls+(set.has(v)?' on':'');b.innerHTML=fn(v);b.onclick=()=>{set.has(v)?set.delete(v):set.add(v);b.classList.toggle('on',set.has(v));state.page=1;reset();renderRows(true);};w.appendChild(b);});}
function filters(){chips('.level-chips',unique(data.rows.map(r=>Number(r.level)||0).filter(Boolean)).sort((a,b)=>a-b),state.levels,v=>esc(ROMAN[v]||v),'level-chip');chips('.nation-chips',unique(data.rows.map(r=>r.nation||'').filter(Boolean)).sort(),state.nations,nation,'nation-chip');chips('.type-chips',unique(data.rows.map(r=>r.type||'').filter(Boolean)).sort(),state.types,v=>typeIcon(v,false),'type-chip');}
function filtered(){let a=data.rows.filter(r=>(!state.levels.size||state.levels.has(Number(r.level)))&&(!state.nations.size||state.nations.has(r.nation))&&(!state.types.size||state.types.has(r.type))&&(!state.owned||r.owned)&&(!state.search||nameOf(r).toLowerCase().indexOf(state.search)>=0)),k=state.sort,d=state.desc?-1:1;a.sort((x,y)=>{let A=x[k],B=y[k];if(A==null)A=-Infinity;if(B==null)B=-Infinity;if(typeof A==='string'){A=A.toLowerCase();B=String(B||'').toLowerCase();}if(A<B)return-d;if(A>B)return d;return nameOf(x).localeCompare(nameOf(y));});return a;}
function thresholds(rows){let ids=[];rows.forEach(r=>{if(ids.length<PAGE&&!(r.thirdClass>0&&r.secondClass>0&&r.firstClass>0&&r.aceTanker>0))ids.push(r.id);});if(ids.length)try{let m=observer.model;if(m&&m.onNeedThresholds)m.onNeedThresholds({ids:ids.join(',')});}catch(e){}}
function renderRows(resetScroll){let r=root(),all=filtered(),pages=Math.max(1,Math.ceil(all.length/PAGE));if(state.page>pages)state.page=pages;if(resetScroll)state.scrollTop=0;let start=(state.page-1)*PAGE,page=all.slice(start,start+PAGE),w=r.querySelector('.rows'),keep=state.scrollTop;if(!page.length)w.innerHTML='<div class="empty">Немає танків за вибраними фільтрами</div>';else w.innerHTML=page.map((x,i)=>'<div class="row"><span class="muted">'+(start+i+1)+'</span><span class="inq-tank-cell" title="'+esc(nameOf(x))+'"><span class="inq-tank-name">'+esc(nameOf(x))+'</span></span><span>'+esc(ROMAN[Number(x.level)]||x.level||'—')+'</span><span>'+typeIcon(x.type,true)+'</span><span class="mastery-cell">'+mastery(x.mastery,'row-mastery-icon')+'</span><span>'+num(x.thirdClass)+'</span><span>'+num(x.secondClass)+'</span><span>'+num(x.firstClass)+'</span><span>'+num(x.aceTanker)+'</span></div>').join('');w.scrollTop=keep;state.scrollTop=w.scrollTop||keep||0;r.querySelector('.count').textContent='Показано '+page.length+' з '+all.length+' (усього '+data.total+')';let p=r.querySelector('.pager');p.innerHTML='';function add(t,n,on){let b=document.createElement('button');b.className='page'+(on?' on':'');b.textContent=t;b.disabled=n<1||n>pages;b.onclick=()=>{state.page=n;reset();renderRows(true);};p.appendChild(b);}add('‹',state.page-1,false);let f=Math.max(1,state.page-2),to=Math.min(pages,f+4);f=Math.max(1,to-4);for(let i=f;i<=to;i++)add(String(i),i,i===state.page);add('›',state.page+1,false);thresholds(page);}
function render(model){let r=root();if(!model)return;resize(model.surfaceWidth,model.surfaceHeight);r.style.left=Math.max(0,Math.round((Number(model.surfaceWidth)-W)/2))+'px';r.style.top=Math.max(0,Math.round((Number(model.surfaceHeight)-H)/2))+'px';let raw=String(model.payload||'{"rows":[],"total":0}');if(raw===lastPayload)return;lastPayload=raw;try{data=JSON.parse(raw);}catch(e){data={rows:[],total:0};}if(!Array.isArray(data.rows))data.rows=[];filters();renderRows(false);}
document.addEventListener('keydown',function(e){if(e.key==='Escape'||e.keyCode===27){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();closeStats();return false;}},true);
resize(W,H);observer.onUpdate(render);observer.subscribe();render(observer.model);
